name: Deploy Node Application

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t ranacode6/ec2-nodejs .
      - name: Pulish Image to Docker Hub
        run: docker push ranacode6/ec2-nodejs:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from the Docker Hub
        run: docker pull ranacode6/ec2-nodejs:latest
      - name: Delete Docker Container
        run: docker rm -f ec2-nodejs-container
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name ec2-nodejs-container -e MONGODB_URI='${{ secrets.MONGODB_URI }}' -e JWT_SECRET='${{secrets.JWT_SECRET}}' -e CLIENT_URL='${{ secrets.CLIENT_URL}}' ranacode6/ec2-nodejs
